### ISSUE TITLE
Build failure (file not found) on Linx/ppc64 and FreeBSD-10.1/amd64

### ISSUE THREAD

**Issue by PHHargrove** [Intrepid/clang-upc#72]
My FreeBSD-10.1 builds now fail as follows:
```
[ 87%] Building CXX object tools/clang/tools/ast-test/CMakeFiles/ast-test.dir/ast-test.cpp.o
/home/phargrov/upcnightly/llvm-upc/src/tools/clang/tools/ast-test/ast-test.cpp:23:10: fatal error: 
      'llvm/ADT/OwningPtr.h' file not found
#include "llvm/ADT/OwningPtr.h"
         ^
1 error generated.
tools/clang/tools/ast-test/CMakeFiles/ast-test.dir/build.make:54: recipe for target 'tools/clang/tools/ast-test/CMakeFiles/ast-test.dir/ast-test.cpp.o' failed
```

**Comment by swatanabe** [comment]
AMDG

On 02/01/2015 04:20 PM, Paul H. Hargrove wrote:
> My FreeBSD-10.1 builds now fail as follows:
> ```
> [ 87%] Building CXX object tools/clang/tools/ast-test/CMakeFiles/ast-test.dir/ast-test.cpp.o
> /home/phargrov/upcnightly/llvm-upc/src/tools/clang/tools/ast-test/ast-test.cpp:23:10: fatal error: 
>       'llvm/ADT/OwningPtr.h' file not found
> #include "llvm/ADT/OwningPtr.h"
>          ^
> 1 error generated.
> tools/clang/tools/ast-test/CMakeFiles/ast-test.dir/build.make:54: recipe for target 'tools/clang/tools/ast-test/CMakeFiles/ast-test.dir/ast-test.cpp.o' failed
> ```
> 

OwningPtr was removed in the latest version of clang.
It should be replaced with std::unique_ptr.

In Christ,
Steven Watanabe

**Comment by PHHargrove** [comment]
Also seen on  Linux/ppc64 platform
