### ISSUE TITLE
Build failure (no rule to make target) on Linux/x86-64

### ISSUE THREAD

**Issue by PHHargrove** [Intrepid/clang-upc#73]
Not sure what makes this particular Linux/x86-64 system different from others, but I see the following reproducible failure:
```
llvm[4]: Compiling Transform.cpp for Release+Asserts build
make[4]: *** No rule to make target `/global/scratch2/sd/hargrove/llvm-upc/bld/Release+Asserts/lib/libclangRewriteCore.a', needed by `/global/scratch2/sd/hargrove/llvm-upc/bld/Release+Asserts/bin/clang-upc2c'.  Stop.
```

This is on Carver, a NERSC system to which Nenad and Gary have access.
The build and logs are in `/global/scratch2/sd/hargrove/llvm-upc/{bld,log}`
I am using `module load python/2.7.3 gcc-ftg` to get recent python and gcc in $PATH.
I am using configure (not cmake) and passing only `--prefix=...` and the following options
```
  --disable-jit --disable-docs --enable-keep-symbols \
       --enable-clang-upc2c --enable-targets=host   --enable-optimized
```

**Comment by PHHargrove** [comment]
I've now seen this on at least 2 more Linux systems which are using configure (with similar args) rather than cmake.

**Comment by nenadv** [comment]
Fixed by this commit in upc2c:https://github.com/Intrepid/upc2c/commit/5d71d6c01a43cb60a5b97893ff8a68d38015cc5a
