### ISSUE TITLE
"ld: cannot find -lupc" on OpenBSD

### ISSUE THREAD

**Issue by PHHargrove** [Intrepid/clang-upc#87]
Last night was the first run of clang-upc on OpenBSD since the 3.8 merge.
Every single compilation failed to link, as shown here:
```
/home/phargrov/upcnightly/llvm-upc/bin/clang-upc -Wno-duplicate-decl-specifier -Werror=pointer-arith -g   -DSTDOUT_OUTPUT -lm -o pingpongUPC pingpongUPC.c
/usr/bin/ld: cannot find -lupc
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I am too busy with other things to track this down myself, but suspect the merge lost some change(s) I had committed in `lib/Driver/{Tools,ToolChains}.cpp` or similar (for instance in d2165782)

**Comment by swatanabe** [comment]
AMDG

  I think I fixed this, but I can't really test it myself.

In Christ,
Steven Watanabe

**Comment by PHHargrove** [comment]
I will be test now.
-Paul

**Comment by PHHargrove** [comment]
Works for me 👍 

Thanks,
-Paul
